export default {
  clients: [
    {
      idx: "0",
      name: "蜂鳥金融科技股份有限公司",
      number: "28114742",
      address: "新竹市東區力行一路1號1樓A2-A12-7",
      city: "新竹市",
      location: "東區",
      category: ["自助儲物空間業", "第三方支付服務業", "投資顧問業"],
      capital: "500000",
      people: "謝松宇",
      date: "1090313",
      industry: ["未分類其他資訊服務"],
      nearest: "展業竹成通訊處",
      sec_nearest: "展業竹市通訊處",
    },
    {
      idx: "1",
      name: "黑澤科技股份有限公司",
      number: "28114763",
      address: "新竹市工業東二路2-3號3樓",
      city: "新竹市",
      location: "東區",
      category: ["投資顧問業"],
      capital: "11000000",
      people: "汪光夏",
      date: "1090217",
      industry: ["其他未分類電子零組件製造"],
      nearest: "展業竹成通訊處",
      sec_nearest: "展業竹市通訊處",
    },
    {
      idx: "2",
      name: "鑫長虹電子股份有限公司",
      number: "29187736",
      address: "高雄市楠梓區楠梓加工出口區新開發路12號3樓",
      city: "高雄市",
      location: "楠梓區",
      category: ["產品設計業", "電子支付業"],
      capital: "20000000",
      people: "張一辰",
      date: "1090306",
      industry: [
        "未分類其他技術檢測及分析服務",
        "其他未分類電子零組件製造",
        "其他電子、通訊設備及其零組件批發",
        "其他化學原材料及其製品批發",
      ],
      nearest: "展業竹成通訊處",
      sec_nearest: "展業竹市通訊處",
    },
    {
      idx: "3",
      name: "西澤科技股份有限公司",
      number: "29187738",
      address: "新竹市工業東二路2-3號3樓",
      city: "新竹市",
      location: "西區",
      category: ["其他未分類電子零組件製造"],
      capital: "130000",
      people: "汪夏",
      date: "1090307",
      industry: ["其他未分類電子零組件製造"],
      nearest: "展業竹成通訊處",
      sec_nearest: "展業竹市通訊處",
    },
  ],
  cities: [
    {
      id: "01",
      name: "臺北市",
      dist: "北區",
    },
    {
      id: "02",
      name: "新北市",
      dist: "北區",
    },
    {
      id: "03",
      name: "基隆市",
      dist: "北區",
    },
    {
      id: "04",
      name: "桃園市",
      dist: "北區",
    },
    {
      id: "05",
      name: "新竹市",
      dist: "北區",
    },
    {
      id: "06",
      name: "新竹縣",
      dist: "北區",
    },
    {
      id: "07",
      name: "宜蘭縣",
      dist: "北區",
    },
    {
      id: "08",
      name: "臺中市",
      dist: "中區",
    },
    {
      id: "09",
      name: "苗栗縣",
      dist: "中區",
    },
    {
      id: "10",
      name: "彰化縣",
      dist: "中區",
    },
    {
      id: "11",
      name: "南投縣",
      dist: "中區",
    },
    {
      id: "12",
      name: "雲林縣",
      dist: "中區",
    },
    {
      id: "13",
      name: "臺南市",
      dist: "南區",
    },
    {
      id: "14",
      name: "高雄市",
      dist: "南區",
    },
    {
      id: "15",
      name: "嘉義市",
      dist: "南區",
    },
    {
      id: "16",
      name: "嘉義縣",
      dist: "南區",
    },
    {
      id: "17",
      name: "屏東縣",
      dist: "南區",
    },
    {
      id: "18",
      name: "澎湖縣",
      dist: "南區",
    },
    {
      id: "19",
      name: "臺東縣",
      dist: "東區",
    },
    {
      id: "20",
      name: "花蓮縣",
      dist: "東區",
    },
    {
      id: "21",
      name: "金門縣",
      dist: "南區",
    },
    {
      id: "22",
      name: "連江縣",
      dist: "南區",
    },
  ],
};
